import asyncio
import json
import sys

import ollama

from mcp import ClientSession, StdioServerParameters
from mcp.client.stdio import stdio_client


# ============================================================
# CONFIGURATION
# ============================================================

MODEL = "qwen3.5:2b"

# Maximum evidence sent to Qwen for final answer generation.
MAX_EVIDENCE_LENGTH = 8000

# Maximum number of tokens generated by Qwen.
MAX_OUTPUT_TOKENS = 300


# ============================================================
# CLEAN QWEN JSON RESPONSE
# ============================================================

def clean_json_response(response_text):

    response_text = response_text.strip()

    # Remove Markdown code fences if Qwen adds them.
    if response_text.startswith("```"):

        lines = response_text.splitlines()

        # Remove opening ```json or ```
        if lines:
            lines = lines[1:]

        # Remove closing ```
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]

        response_text = "\n".join(lines).strip()

    return response_text


# ============================================================
# ASK QWEN TO SELECT MCP TOOL
# ============================================================

def choose_tool(question, tools_text):

    prompt = f"""
You are an AI research assistant.

Choose the ONE best MCP tool for the user's question.

Available MCP tools:

{tools_text}

User question:

{question}

Tool selection rules:

1. search_papers
   Use for general research questions when the relevant paper
   is not known.

2. get_paper_metadata
   Use when the user asks for paper title, author, page count,
   or indexed chunks.

3. get_page
   Use when the user asks about a specific page of a specific
   paper.

4. search_within_paper
   Use when the user asks for information from one specific
   paper.

5. compare_papers_tool
   Use when the user asks to compare two research papers.

Return ONLY valid JSON.

Do NOT use Markdown.
Do NOT use ```json.
Do NOT explain your decision.

Return exactly:

{{
    "tool": "tool_name",
    "arguments": {{
        "argument_name": "value"
    }}
}}
"""

    response = ollama.chat(
        model=MODEL,
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ],
        think=False,
        options={
            "temperature": 0.1,
            "num_predict": 200
        }
    )

    return response["message"]["content"]


# ============================================================
# GENERATE FINAL GROUNDED ANSWER
# ============================================================

def generate_final_answer(question, evidence):

    prompt = f"""
You are an AI research assistant.

Answer the user's question using ONLY the retrieved evidence.

User question:
{question}

Retrieved evidence:
{evidence}

Instructions:

- Give a clear and concise answer.
- Use only information supported by the evidence.
- Do not invent facts.
- Explain the answer in simple academic language.
- Mention the paper and page when useful.
- If the evidence is insufficient, say so.
- Do not mention MCP, ChromaDB, embeddings, reranking,
  or internal system details.

Answer:
"""

    try:

        response = ollama.chat(
            model=MODEL,
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            think=False,
            options={
                "temperature": 0.2,
                "num_predict": MAX_OUTPUT_TOKENS
            }
        )

        answer = response["message"]["content"]

        return answer.strip()

    except Exception as error:

        return (
            "Unable to generate the final answer.\n"
            f"Error: {error}"
        )


# ============================================================
# MAIN AGENT
# ============================================================

async def main():

    # ========================================================
    # START MCP SERVER
    # ========================================================

    server_params = StdioServerParameters(
        command=sys.executable,
        args=["mcp_server.py"],
    )

    async with stdio_client(server_params) as (read, write):

        async with ClientSession(read, write) as session:

            # =================================================
            # INITIALIZE MCP CONNECTION
            # =================================================

            await session.initialize()

            # =================================================
            # DISCOVER MCP TOOLS
            # =================================================

            tools_result = await session.list_tools()

            print("\n===== MCP TOOLS =====\n")

            for tool in tools_result.tools:

                print(
                    f"- {tool.name}"
                )

            # =================================================
            # PREPARE TOOL DESCRIPTIONS
            # =================================================

            tool_descriptions = []

            for tool in tools_result.tools:

                tool_descriptions.append(
                    {
                        "name": tool.name,
                        "description": tool.description,
                        "input_schema": tool.input_schema,
                    }
                )

            tools_text = json.dumps(
                tool_descriptions,
                indent=2
            )

            # =================================================
            # USER QUESTION
            # =================================================

            question = input(
                "\nEnter your research question: "
            )

            # =================================================
            # QWEN TOOL DECISION
            # =================================================

            print(
                "\n===== QWEN TOOL DECISION =====\n"
            )

            qwen_response = choose_tool(
                question,
                tools_text
            )

            print(qwen_response)

            # =================================================
            # CLEAN JSON RESPONSE
            # =================================================

            cleaned_response = clean_json_response(
                qwen_response
            )

            # =================================================
            # PARSE TOOL DECISION
            # =================================================

            try:

                decision = json.loads(
                    cleaned_response
                )

            except json.JSONDecodeError as error:

                print(
                    "\nERROR: Could not parse Qwen response "
                    "as JSON."
                )

                print(
                    f"JSON error: {error}"
                )

                print(
                    "\nCleaned response:"
                )

                print(cleaned_response)

                return

            # =================================================
            # EXTRACT TOOL NAME
            # =================================================

            tool_name = decision.get(
                "tool"
            )

            arguments = decision.get(
                "arguments",
                {}
            )

            # =================================================
            # VALIDATE TOOL
            # =================================================

            available_tools = {
                tool.name
                for tool in tools_result.tools
            }

            if tool_name not in available_tools:

                print(
                    f"\nERROR: Invalid tool selected: "
                    f"{tool_name}"
                )

                print(
                    "\nAvailable tools:"
                )

                for name in available_tools:

                    print(
                        f"- {name}"
                    )

                return

            # =================================================
            # DISPLAY SELECTED TOOL
            # =================================================

            print(
                f"\nSelected MCP tool: {tool_name}"
            )

            print(
                f"Arguments: {arguments}"
            )

            # =================================================
            # EXECUTE MCP TOOL
            # =================================================

            print(
                f"\n===== EXECUTING MCP TOOL: "
                f"{tool_name} =====\n"
            )

            result = await session.call_tool(
                tool_name,
                arguments=arguments
            )

            # =================================================
            # EXTRACT MCP RESULT
            # =================================================

            evidence_parts = []

            for content in result.content:

                if hasattr(content, "text"):

                    evidence_parts.append(
                        content.text
                    )

            evidence = "\n".join(
                evidence_parts
            )

            # =================================================
            # CHECK MCP RESULT
            # =================================================

            if not evidence.strip():

                print(
                    "\nNo evidence was returned by "
                    "the MCP tool."
                )

                return

            # =================================================
            # LIMIT EVIDENCE SIZE
            # =================================================

            if len(evidence) > MAX_EVIDENCE_LENGTH:

                print(
                    f"\nMCP returned "
                    f"{len(evidence)} characters."
                )

                print(
                    f"Limiting evidence to "
                    f"{MAX_EVIDENCE_LENGTH} characters "
                    f"for Qwen."
                )

                evidence = evidence[
                    :MAX_EVIDENCE_LENGTH
                ]

            # =================================================
            # DISPLAY MCP RESULT
            # =================================================

            print(
                "\n===== MCP TOOL RESULT =====\n"
            )

            print(evidence)

            # =================================================
            # GENERATE FINAL ANSWER
            # =================================================

            print(
                "\n===== QWEN FINAL ANSWER =====\n"
            )

            final_answer = generate_final_answer(
                question,
                evidence
            )

            if final_answer:

                print(
                    final_answer
                )

            else:

                print(
                    "Qwen returned an empty answer."
                )


# ============================================================
# PROGRAM ENTRY POINT
# ============================================================

if __name__ == "__main__":

    asyncio.run(main())